### ISSUE TITLE
Manifest (bed) file for custom library kit

### ISSUE THREAD

**Issue by jaudoux** [chrisamiller/aml31SuppSite#1]
Dear all,

I have recently been granted access to the AM31 sequencing data on dbGAP, and I was wondering where I could find the manifest (bed) files of the custom kit used in this study. For example the IDT "AML RMG set" or the NimbleGene custom capture (200k sites). I have search on the dbGAP public data [FTP](ftp://ftp.ncbi.nlm.nih.gov/dbgap/studies/phs000159), but I was not able to find these files.

Best,
Jérôme.

**Comment by malachig** [comment]
This information has now been added to the supplementary website for this paper here:

http://griffithlab.org/aml31/sequence.html

**Comment by jaudoux** [comment]
Thanks a lot @malachig, for the files and the reactivity!
